export { default as IconAI } from './IconAI'
export { default as IconAnimation } from './IconAnimation'
export { default as IconApi } from './IconApi'
export { default as IconCSS } from './IconCSS'
export { default as IconCloseCircle } from './IconCloseCircle'
export { default as IconColor } from './IconColor'
export { default as IconEmail } from './IconEmail'
export { default as IconFont } from './IconFont'
export { default as IconIcon } from './IconIcon'
export { default as IconIlustration } from './IconIlustration'
export { default as IconImage } from './IconImage'
export { default as IconInformation } from './IconInformation'
export { default as IconJavascript } from './IconJavascript'
export { default as IconOtherDesign } from './IconOtherDesign'
export { default as IconReact } from './IconReact'
export { default as IconTypescript } from './IconTypescript'
export { default as IconWebHosting } from './IconWebHosting'

